target "TNSDateInitializerDemo" do
    pod "NSDate-TNSDateInitializer", :path => "../NSDate-TNSDateInitializer.podspec"
end

target "TNSDateInitializerDemoTests" do
   pod 'Kiwi/XCTest', '~> 2.2.3'
end
